

public class DefaultCities {
    public static City[] defaultCities = new City[]{
        new City("Seattle", 1904),
        new City("Portland", 1983),
        new City("SanFrancisco", 2086),
        new City("LosAngeles", 1974),
        new City("LasVegas", 1706),
        new City("Boise", 1651),
        new City("SaltLakeCity", 1356),
        new City("Pheonix", 1688),
        new City("Cheyenne", 919),
        new City("Denver", 960),
        new City("Albuquerque", 1273),
        new City("Fargo", 504),
        new City("Omaha", 425),
        new City("KansasCity", 484),
        new City("OklahomaCity", 835),
        new City("Dallas", 989),
        new City("Houston", 1135),
        new City("SanAntonio", 1299),
        new City("NewOrleans", 1035),
        new City("StLouis", 359),
        new City("DesMoines", 292),
        new City("Minneapolis", 270),
        new City("Milwaukee", 79),
        new City("GreenBay", 136),
        new City("Chicago", 147),
        new City("Indianapolis", 330),
        new City("Detroit", 428),
        new City("Cleveland", 491),
        new City("Louisville", 445),
        new City("Nashville", 619),
        new City("Atlanta", 863),
        new City("Orlando", 1302),
        new City("Miami", 1525),
        new City("Charleston", 1058),
        new City("Charlotte", 903),
        new City("WashingtonDC", 843),
        new City("Baltimore", 848),
        new City("Philadelphia", 904),
        new City("Pittsburgh", 607),
        new City("NewYork", 935),
        new City("Buffalo", 679),
        new City("Boston", 1129)

    };
}
